# Example: OpenAI-only deployment
# This configuration uses only OpenAI for AI responses

# Enable OpenAI
openai:
  enabled: true
  apiKey: "sk-proj-your-openai-api-key-here"
  model: "gpt-3.5-turbo"
  maxTokens: 500
  temperature: 0.7

# Disable Ollama
ollama:
  enabled: false

# Backend configuration
backend:
  enabled: true
  replicaCount: 3
  env:
    NODE_ENV: "production"
    PORT: 3001
    ALLOWED_ORIGINS: "https://yourdomain.com"
    MAX_REQUESTS_PER_MINUTE: 120
    MAX_REQUESTS_PER_HOUR: 2000

# Frontend configuration
frontend:
  enabled: true
  replicaCount: 2
  widget:
    theme: "dark"
    position: "bottom-right"
    autoOpen: false

# Ingress configuration
ingress:
  enabled: true
  hosts:
    - host: chatkit.yourdomain.com
      paths:
        - path: /
          pathType: Prefix
          service: frontend
        - path: /api
          pathType: Prefix
          service: backend
