{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chatkit.fullname" . }}-frontend
  labels:
    {{- include "chatkit.frontend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      {{- include "chatkit.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- with .Values.annotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "chatkit.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.security.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chatkit.serviceAccountName" . }}
      containers:
        - name: frontend
          {{- with .Values.security.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if .Values.frontend.customWebsite.enabled }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.customWebsite.image.repository }}:{{ .Values.frontend.customWebsite.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.customWebsite.image.pullPolicy }}
          {{- else }}
          image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.targetPort }}
              protocol: TCP
          env:
            - name: CHATKIT_API_URL
              value: {{ include "chatkit.backend.apiUrl" . | quote }}
            - name: CHATKIT_THEME
              value: {{ .Values.frontend.widget.theme | quote }}
            - name: CHATKIT_POSITION
              value: {{ .Values.frontend.widget.position | quote }}
            - name: CHATKIT_AUTO_OPEN
              value: {{ .Values.frontend.widget.autoOpen | quote }}
            - name: CHATKIT_ENABLE_TYPING
              value: {{ .Values.frontend.widget.enableTyping | quote }}
            - name: CHATKIT_ENABLE_SOUND
              value: {{ .Values.frontend.widget.enableSound | quote }}
            - name: CHATKIT_MAX_MESSAGES
              value: {{ .Values.frontend.widget.maxMessages | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
