{{- if .Values.ollama.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "chatkit.ollama.serviceName" . }}
  labels:
    {{- include "chatkit.ollama.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ollama.service.type }}
  ports:
    - port: {{ .Values.ollama.service.port }}
      targetPort: {{ .Values.ollama.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "chatkit.ollama.selectorLabels" . | nindent 4 }}
{{- end }}
