{{- if .Values.security.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "chatkit.fullname" . }}-backend
  labels:
    {{- include "chatkit.backend.labels" . | nindent 4 }}
spec:
  {{- if .Values.security.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.security.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.security.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.security.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "chatkit.backend.selectorLabels" . | nindent 6 }}
{{- end }}
